# -*- coding: utf-8 -*-
"""Assignment_Loops_Lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LGZ5SQKT0TFsFO8823fhZrPjiy0ppQ-W

# Assignment: Python Loops and Lists
## - By Raman Butta

This notebook is in fulfilment of an assignment of 10 questions on Python loops and lists.

Q1. Find the sum of elements in a list.
Example: l = [1, 2, 3, 4] → Output: 10
"""

mylist =[]
total_sum = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break # loop will break when user presses q
  number = int(user_input)  # type casting to int
  mylist.append(number)     # input number appended to mylist
  total_sum += number       # total_sum updated

print(f"The list is {mylist}")
print(f"The sum is {total_sum}")

"""Q2. Find the sum of squares of elements in a list.
Example: l = [1, 2, 3] → Output: 14
"""

mylist =[]
total_sum = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)
  total_sum += (number*number)    # square of number added

print(f"The list is {mylist}")
print(f"The sum of squares is {total_sum}")

"""Q3. Find the product of all elements in a list.
Example: l = [2, 3, 4] → Output: 24
"""

mylist =[]
product = 1
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)
  product *= number     # number multiplied with existing product

print(f"The list is {mylist}")
print(f"The product of numbers is {product}")

"""Q4. Find the largest element in a list.
Example: l = [5, 7, 2, 9, 1] → Output: 9
"""

mylist =[]
largest_num = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)
  largest_num = max(mylist)   # largest number of list

print(f"The list is {mylist}")
print(f"The largest number is {largest_num}")

"""Q5. Find the smallest element in a list.
Example: l = [5, 7, 2, 9, 1] → Output: 1
"""

mylist =[]
largest_num = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)
  largest_num = min(mylist)   # smallest number of list

print(f"The list is {mylist}")
print(f"The smallest number is {largest_num}")

"""Q6. Count how many even numbers are in a list.
Example: l = [1, 2, 3, 4, 6] → Output: 3
"""

mylist =[]
even_nums = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)
  if number%2==0:       # if number is divisible by 2, increment even_nums
    even_nums+=1

print(f"The list is {mylist}")
print(f"The no. of even numbers is {even_nums}")

"""Q7. Count how many odd numbers are in a list.
Example: l = [1, 2, 3, 4, 6] → Output: 2
"""

mylist =[]
odd_nums = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)
  if number%2!=0:     # if number is not divisible by 2, increment odd_nums
    odd_nums+=1

print(f"The list is {mylist}")
print(f"The no. of odd numbers is {odd_nums}")

"""Q8. Find the sum of even numbers in a list.
Example: l = [1, 2, 3, 4, 6] → Output: 12
"""

mylist =[]
even_sums = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)
  if number%2==0:
    even_sums+=number     # if number is divisible by 2, add it to even_sums

print(f"The list is {mylist}")
print(f"The sum of even numbers is {even_sums}")

"""Q9. Find the sum of odd numbers in a list.
Example: l = [1, 2, 3, 4, 6] → Output: 4
"""

mylist =[]
odd_sums = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)
  if number%2!=0:
    odd_sums+=number      # if number is not divisible by 2, add it to odd_sums

print(f"The list is {mylist}")
print(f"The sum of odd numbers is {odd_sums}")

"""Q10. Reverse a list using a while loop.
Example: l = [1, 2, 3, 4] → Output: [4, 3, 2, 1]
"""

mylist =[]
odd_sums = 0
print("Enter numbers one by one, pressing Enter after each. Type q to finish")

while True:
  user_input=input("Enter a number: ")
  if (user_input=='q'): break
  number = int(user_input)
  mylist.append(number)

revlist = []
i=len(mylist)-1
while (i>=0):                 # loop in reverse and append numbers to revlist
 revlist.append(mylist[i])
 i-=1

print(f"The list is {mylist}")
print(f"The reversed list is {revlist}")
